server:
  port: 80
spring:
  application:
    name: redis-demo
  redis:
    host: cloud.aliyun.com
    port: 6379
    password: 1234
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100ms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/redis-demo?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
  jackson:
    default-property-inclusion: non_null # JSON 处理时忽略非空字段
mybatis-plus:
  type-aliases-package: org.example.entity # 别名扫描包
logging:
  level:
    org.example: debug

file:
  path: D:/Github/tmp/file
  domain: http://nav.xiaozaiz.xyz/demo/pages/file/save/

