server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fantuan?useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.61.155
    port: 5672
    virtual-host: /
    username: root
    password: 1234
logging:
  level:
    org.example: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: org.example.es.hotel.pojo